# Generated by Django 5.0.6 on 2024-07-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.PositiveIntegerField()),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("school_class", "subject")},
            },
        ),
    ]
