# Generated by Django 5.0.7 on 2024-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_alter_subject_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("warning", "Avertissement"),
                            ("event", "Évènement"),
                            ("danger", "Danger"),
                            ("info", "Information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
