# Generated by Django 5.0.7 on 2024-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                choices=[
                    ("Histoire-Géographie", "Histoire-Géographie"),
                    ("Physique-Chimie", "Physique-Chimie"),
                    ("Français", "Français"),
                    ("Anglais", "Anglais"),
                    ("Langue Vivante 2", "Langue Vivante 2"),
                    ("Mathématiques", "Mathématiques"),
                    ("Éducation Civique et Morale", "Éducation Civique et Morale"),
                    ("Philosophie", "Philosophie"),
                    ("Arts Plastiques", "Arts Plastiques"),
                    ("Musique", "Musique"),
                    (
                        "Éducation Physique et Sportive",
                        "Éducation Physique et Sportive",
                    ),
                    ("Natation", "Natation"),
                ],
                max_length=100,
            ),
        ),
    ]
