# Generated by Django 5.0.6 on 2024-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration",
            "0005_schedule_day_of_week_alter_schedule_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (1, "Lundi"),
                    (2, "Mardi"),
                    (3, "Mercredi"),
                    (4, "Jeudi"),
                    (5, "Vendredi"),
                ],
                default=1,
            ),
        ),
    ]
