# Generated by Django 5.0.6 on 2024-07-17 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0007_alter_schedule_day_of_week"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
