# Generated by Django 5.0.7 on 2024-07-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagerie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
