# Generated by Django 5.0.6 on 2024-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="fichier/"),
        ),
    ]
