# Generated by Django 5.0.7 on 2024-07-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagerie", "0002_alter_message_body_alter_message_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(max_length=250),
        ),
    ]
