# Generated by Django 5.0.6 on 2024-06-21 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("GP", "Gospel"),
                            ("PR", "Praising"),
                            ("WSH", "Worship"),
                        ],
                        max_length=5,
                    ),
                ),
                ("biography", models.CharField(max_length=1000)),
                (
                    "year_formed",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2021),
                        ]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("official_homepage", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
