# Generated by Django 5.0.7 on 2024-12-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_parent', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.parent'),
        ),
    ]
