"""
Django settings for lsy_website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import environ


#env = environ.Env()
#env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# LOCAL ENVIRONMENT SETTINGS
SECRET_KEY = 'django-insecure-k0th%jqik@rn*e@$hoqpwfpe_jj)rv4=3$$l3$w68&x!8a2&8b'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'marceldevtest@gmail.com'
EMAIL_HOST_PASSWORD = 'fszomdfgibjvkjya'
CONTACT_EMAIL = ['josemarcelassie@gmail.com', 'marceldevtest@gmail.com']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""
# DEPLOYMENT ENVIRONMENT SETTINGS

SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS","").split(" ")
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'marceldevtest@gmail.com'
EMAIL_HOST_PASSWORD = 'fszomdfgibjvkjya'
CONTACT_EMAIL = ['josemarcelassie@gmail.com', 'marceldevtest@gmail.com']
DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}
"""


# Languages
LANGUAGE_CODE = 'fr-FR'

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accueil',
    'authentication',
    'student',
    'administration',
    'teacher',
    'messagerie',
    'admin_teacher',
    'admin_student',
    'admin_parent',
    'parent',
    'admin_website',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lsy_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accueil.context_processors.base_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'lsy_website.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'authentication.validators.MaxLengthValidator',
        'OPTIONS': {
            'max_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'authentication.validators.PasswordComplexityValidator',
    }
]




# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'authentication.User'

LOGIN_URL = 'login'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


JAZZMIN_SETTINGS = {
    "site_title": "Administrateur",
    "site_header": "Marcel Assie",
    "site_brand": "Marcel Assie",
    "welcome_sign": "Bienvenue dans l'administration du Portail du LSY",
    "site_logo": "images/admin.png",  # Ajoutez le chemin à votre logo
    "site_logo_classes": "img-circle",  # Pour un logo circulaire
    "site_icon": "images/favicon.ico",  # Ajoutez un favicon
    "copyright": "©  Lycée Scientifique de Yamoussoukro",
    "user_avatar": None,
    "custom_css": "admin/style_admin.css",
    "icons": {
        "auth.User": "fas fa-user",  # Exemple d'icône personnalisée pour un modèle
        "auth.Group": "fas fa-users",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",  # Thème de base, essayez d'autres comme "flatly", "journal", etc.
    "navbar": "navbar-dark bg-primary",  # Barre de navigation en haut
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",  # Barre latérale
    "sidebar_nav_compact_style": True,  # Pour un style plus compact
    "sidebar_fixed": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "success": "btn-success",
        "warning": "btn-warning",
        "danger": "btn-danger",
    },
    "actions_sticky_top": True,  # Pour que les actions restent en haut lorsque vous faites défiler la page
}

