# Generated by Django 5.0.7 on 2025-07-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(choices=[('school', 'À l’école'), ('home', 'En famille / à la maison'), ('road', 'Sur le chemin de l’école'), ('social', 'En ligne / sur les réseaux'), ('public_space', 'Dans l’espace public'), ('internat', 'À l’internat'), ('activite', 'Pendant une activité périscolaire')], default='school', max_length=20)),
                ('other_place', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(choices=[('physique', 'Violence physique'), ('verbale', 'Violence verbale'), ('psychologique', 'Violence psychologique'), ('sexuelle', 'Violence sexuelle'), ('cyber', 'Cyberharcèlement'), ('discrimination', 'Discrimination'), ('negligence', 'Négligence éducative'), ('intimidation', 'Intimidation / menaces')], default='verbale', max_length=20)),
                ('other_reason', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description libre des faits')),
                ('perpetrator', models.CharField(blank=True, help_text='Auteur présumé (élève, adulte, inconnu, etc.)', max_length=50)),
                ('reported_by', models.CharField(blank=True, help_text='Personne ayant signalé les faits', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modérée'), ('high', 'Grave'), ('critical', 'Critique')], default='moderate', max_length=10)),
                ('action_taken', models.TextField(blank=True, help_text='Action(s) entreprise(s) suite au signalement')),
                ('status', models.CharField(choices=[('reported', 'Signalé'), ('investigating', "En cours d'enquête"), ('resolved', 'Résolu'), ('archived', 'Archivé')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
