# Generated by Django 5.0.7 on 2025-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_violence_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violence',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Action(s) entreprise(s) suite au signalement', max_length=200),
        ),
        migrations.AlterField(
            model_name='violence',
            name='description',
            field=models.TextField(blank=True, help_text='Description libre des faits', max_length=200),
        ),
    ]
