# Generated by Django 5.0.7 on 2025-07-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('student', '0003_alter_violence_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violences', to='authentication.student'),
        ),
    ]
