# Generated by Django 5.0.7 on 2024-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="temoignages/", verbose_name="Photo"
            ),
        ),
    ]
