# Generated by Django 5.0.6 on 2024-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="annales/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
