# Generated by Django 5.0.7 on 2024-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_website", "0002_annale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "promotion",
                    models.CharField(max_length=50, verbose_name="Promotion"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Photo",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texte du Témoignage")),
            ],
        ),
    ]
