# Generated by Django 5.0.7 on 2024-08-10 12:11

import admin_website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0002_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(upload_to=admin_website.models.upload_to_actualites),
        ),
        migrations.AlterField(
            model_name='annale',
            name='file',
            field=models.FileField(upload_to=admin_website.models.upload_to_annales),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(upload_to=admin_website.models.upload_to_evenements),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=admin_website.models.upload_to_temoignages, verbose_name='Photo'),
        ),
    ]
